### ISSUE TITLE
ExoPlayer 2 playlist Videos (MP4)

### ISSUE THREAD

**Issue by SopMar** [ayalus/ExoPlayer-2-Example#4]
Hello Ayalus,

Nice work. Can you update this code, to work with Playlist like just take 3 items in a Recyclerview (static only) and start playing first one, once first one is complete auto start second one and we can also tap on prev / next buttons to play the same one. Just like a small portion of YouTube

As I have seen your expertise with ExoPlayer, I believe you already implemented same kind of thing in past, so can you please share with us.

**Comment by ayalus** [comment]
hello SopMar,

I have actually shared everything i've got right here. i've just set up the very basic implementation of ExoPlayer2 and have not continued beyond the code you see. 

Good luck with the tweaking!
